# Generated by Django 5.0.7 on 2024-08-01 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisement",
            options={"verbose_name": "child", "verbose_name_plural": "children"},
        ),
    ]
