# Generated by Django 5.0.7 on 2024-08-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0002_alter_advertisement_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="color",
            field=models.CharField(
                choices=[("RED", "Red")], default="RED", max_length=3
            ),
            preserve_default=False,
        ),
    ]
