# Generated by Django 5.0.7 on 2024-08-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0004_alter_advertisement_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="color",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("WHITE", "White"),
                    ("BLUE", "Blue"),
                    ("BLACK", "Black"),
                    ("GREEN", "Green"),
                    ("GRAY", "Gray"),
                ],
                max_length=12,
            ),
        ),
    ]
