# Generated by Django 5.0.7 on 2024-09-13 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0007_car"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carbrand",
            old_name="brand_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="carmodel",
            old_name="model_name",
            new_name="name",
        ),
    ]
