# Generated by Django 5.0.7 on 2024-09-13 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0008_rename_brand_name_carbrand_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carmodel",
            name="brand",
        ),
        migrations.AddField(
            model_name="carmodel",
            name="carbrand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elanlar.carbrand",
            ),
            preserve_default=False,
        ),
    ]
