# Generated by Django 5.0.7 on 2024-09-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0009_remove_carmodel_brand_carmodel_carbrand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carmodel",
            old_name="carbrand",
            new_name="brand",
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
