# Generated by Django 5.0.7 on 2024-09-13 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0010_rename_carbrand_carmodel_brand_alter_carmodel_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="brand",
            new_name="car_brand",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="model",
            new_name="car_model",
        ),
    ]
