# Generated by Django 5.0.7 on 2024-09-13 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0011_rename_brand_car_car_brand_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carmodel",
            old_name="brand",
            new_name="car_brand",
        ),
    ]
