# Generated by Django 5.0.7 on 2024-09-13 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0012_rename_brand_carmodel_car_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransmissionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="car_model",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="dealer",
        ),
        migrations.RemoveField(
            model_name="review",
            name="advertisement",
        ),
        migrations.RemoveField(
            model_name="review",
            name="customer",
        ),
        migrations.AddField(
            model_name="car",
            name="transmission_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="elanlar.transmissiontype",
                verbose_name="Ötürücü",
            ),
        ),
        migrations.DeleteModel(
            name="Dealer",
        ),
        migrations.DeleteModel(
            name="Advertisement",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
