# Generated by Django 5.0.7 on 2024-09-18 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0013_transmissiontype_remove_advertisement_car_model_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carmodel",
            name="car_brand",
        ),
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.DeleteModel(
            name="TransmissionType",
        ),
        migrations.DeleteModel(
            name="CarBrand",
        ),
        migrations.DeleteModel(
            name="CarModel",
        ),
    ]
