# Generated by Django 5.0.7 on 2024-09-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("elanlar", "0014_remove_carmodel_car_brand_delete_car_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("marka", models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
