# Generated by Django 5.0.7 on 2024-09-18 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0015_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carbrand",
            old_name="username",
            new_name="name",
        ),
    ]
