# Generated by Django 5.0.7 on 2024-09-20 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0016_rename_username_carbrand_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carbrand",
            name="marka",
        ),
        migrations.AddField(
            model_name="carbrand",
            name="country",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "carbrand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elanlar.carbrand",
                    ),
                ),
            ],
        ),
    ]
