# Generated by Django 5.0.7 on 2024-09-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0018_customer_dealer_advertisement_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="advertisement",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="carbrand",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="dealer",
            name="location",
        ),
        migrations.RemoveField(
            model_name="review",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="review",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="review",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.AddField(
            model_name="review",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elanlar.carbrand",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elanlar.customer",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="elanlar.dealer"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elanlar.carmodel",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="elanlar.review"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Advertisement",
        ),
    ]
