# Generated by Django 5.0.7 on 2024-09-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0019_remove_review_advertisement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carmodel",
            name="carbrand",
        ),
        migrations.AddField(
            model_name="carmodel",
            name="brand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="elanlar.carbrand",
            ),
            preserve_default=False,
        ),
    ]
