# Generated by Django 5.0.7 on 2024-09-21 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0020_remove_carmodel_carbrand_carmodel_brand"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dealer",
            new_name="Şeher",
        ),
    ]
