# Generated by Django 5.0.7 on 2024-09-21 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0023_rename_review_valyuta_rename_review_car_valyuta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="İl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="il",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="elanlar.i̇l"
            ),
            preserve_default=False,
        ),
    ]
