# Generated by Django 5.0.7 on 2024-09-22 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0025_reng_yanacaqnövü_ötürücü_car_reng_car_yanacaqnövü_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bannövü",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Süretlerqutusu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Yürüş",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="bannövü",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elanlar.bannövü",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="süretlerqutusu",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elanlar.süretlerqutusu",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="yürüş",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elanlar.yürüş",
            ),
            preserve_default=False,
        ),
    ]
