# Generated by Django 5.0.7 on 2024-09-23 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0027_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Yürüş",
            new_name="BanType",
        ),
        migrations.RenameModel(
            old_name="Bannövü",
            new_name="CarMarch",
        ),
        migrations.RenameModel(
            old_name="Ötürücü",
            new_name="City",
        ),
        migrations.RenameModel(
            old_name="Qiymet",
            new_name="Color",
        ),
        migrations.RenameModel(
            old_name="Valyuta",
            new_name="Currency",
        ),
        migrations.RenameModel(
            old_name="Reng",
            new_name="FuelType",
        ),
        migrations.RenameModel(
            old_name="Yanacaqnövü",
            new_name="GearBox",
        ),
        migrations.RenameModel(
            old_name="İl",
            new_name="Price",
        ),
        migrations.RenameModel(
            old_name="Şeher",
            new_name="Transmitter",
        ),
        migrations.RenameModel(
            old_name="Süretlerqutusu",
            new_name="Year",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="yürüş",
            new_name="bantype",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="bannövü",
            new_name="carmarch",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="ötürücü",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="qiymet",
            new_name="color",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="valyuta",
            new_name="currency",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="reng",
            new_name="fueltype",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="yanacaqnövü",
            new_name="gearbox",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="il",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="şeher",
            new_name="transmitter",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="süretlerqutusu",
            new_name="year",
        ),
    ]
