# Generated by Django 5.0.7 on 2024-09-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0028_rename_yürüş_bantype_rename_bannövü_carmarch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="front_view_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="elanlar/movie/img_cars",
                verbose_name="Ön görünüşü",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="interior_view_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="elanlar/movie/img_cars",
                verbose_name="Ön paneli",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="rear_view_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="elanlar/movie/img_cars",
                verbose_name="Arxa görünüşü",
            ),
        ),
        migrations.CreateModel(
            name="ImageCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="elanlar/movie/img_cars", verbose_name="Şəkil"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elanlar.car",
                        verbose_name="Avtomobil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avtomobil Şəkili",
                "verbose_name_plural": "Avtomobil Şəkilləri",
            },
        ),
    ]
