# Generated by Django 5.0.7 on 2024-09-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0029_car_front_view_image_car_interior_view_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Qiymət"),
        ),
        migrations.DeleteModel(
            name="Price",
        ),
    ]
