# Generated by Django 5.0.7 on 2024-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0030_alter_car_price_delete_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("ads_count", models.PositiveIntegerField()),
                ("logo", models.ImageField(upload_to="logos/")),
            ],
        ),
    ]
