# Generated by Django 5.0.7 on 2024-09-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0034_alter_salon_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Təsdiq"),
        ),
    ]
