# Generated by Django 5.0.7 on 2024-09-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elanlar", "0037_alter_car_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
